# schemachange_config.yml

# SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
# SF_USERNAME: ${{ secrets.SF_USERNAME }}
# SF_ROLE: ${{ secrets.SF_ROLE }}
# SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
# SF_DATABASE: ${{ secrets.SF_DATABASE }}
# SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}

# change-history-table: $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY
# create-change-history-table: true

#same for each env
config-version: 1
root-folder: 'scripts'
modules-folder: null
snowflake-account: ${{ secrets.SF_ACCOUNT }} # for example: XXXXX.west-us.azure
snowflake-warehouse: ${{ secrets.SF_WAREHOUSE }}
create-change-history-table: false
autocommit: false
verbose: true


#changed within each env
snowflake-user: ${{ secrets.SF_USERNAME }}
snowflake-role: ${{ secrets.SF_ROLE }}
change-history-table: 'UTILITY.SCHEMACHANGE.CHANGE_HISTORY'