#same for each env
config-version: 1
root-folder: 'scripts'
modules-folder: null
snowflake-account: 'PV50590.AWS_AP_SOUTHEAST_1.AWS' # for example: XXXXX.west-us.azure
snowflake-warehouse: 'COMPUTE_WH'
create-change-history-table: false
autocommit: false
verbose: true


#changed within each env
snowflake-user: 'MAGNUS'
snowflake-role: 'ACCOUNTADMIN'
change-history-table: 'UTILITY.SCHEMACHANGE.CHANGE_HISTORY'