name: On PR approved for DATA_PRODUCT, call a reusable workflow (prod)

on:
  workflow_dispatch:  
  push:
    branches:
      - master
      - magnus_test_uat
    paths:
      - 'DATA_PRODUCT/**'
    

jobs:
  call-workflow-passing-data:
    environment: prod
    runs-on: ubuntu-latest
    name: Calls a schemachange composite action
    steps:
      - id: schemachange
        uses: CloudMile-Inc/schemachange-action@5a7ac8aeef0353de759d965f2fdc00281b8f1555
        with:
          # DRY_RUN: --dry-run
          SF_DATABASE: SCHEMACHANGE_DEMO #Provide the Snowflake database name
          LOCATION_OF_DDL_SCRIPTS: DATA_PRODUCT
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
          SF_PRIVATE_KEY_FILE_PWD: ${{ secrets.SF_PRIVATE_KEY_FILE_PWD }}