name: Deploy Snowflake Changes

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_tst:
    runs-on: ubuntu-latest
    environment: TST
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dry Run TST
        id: dry_run_tst
        uses: ./.github/workflows/templates/deploy-template.yaml # Assuming the template is in this path
        with:
          snowflake_password: ${{ secrets.SF_PASS }}
          dry_run: '--dry-run'
          env: "tst" # Pass env variable

      - name: Manual Validation TST
        uses: peter-evans/ask-for-approval@v5
        with:
          approvers: ${{ github.repository_owner }} # or specific users/teams
          minimum-approvals: 1
        if: always() && steps.dry_run_tst.outcome == 'success'

      - name: Deploy TST
        uses: ./.github/workflows/templates/deploy-template.yaml # Assuming the template is in this path
        with:
          snowflake_password: ${{ secrets.SF_PASS }}
          dry_run: ''
          env: "tst" # Pass env variable
        if: steps.manual_validation_tst.outputs.approved == 'true'

  deploy_prd:
    runs-on: ubuntu-latest
    environment: PRD
    needs: deploy_tst # Ensure TST deploys before PRD
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dry Run PRD
        id: dry_run_prd
        uses: ./.github/workflows/templates/deploy-template.yaml # Assuming the template is in this path
        with:
          snowflake_password: ${{ secrets.SF_PASS }}
          dry_run: '--dry-run'
          env: "prd" # Pass env variable

      - name: Manual Validation PRD
        uses: peter-evans/ask-for-approval@v5
        with:
          approvers: ${{ github.repository_owner }} # or specific users/teams
          minimum-approvals: 1
        if: always() && steps.dry_run_prd.outcome == 'success'

      - name: Deploy PRD
        uses: ./.github/workflows/templates/deploy-template.yaml # Assuming the template is in this path
        with:
          snowflake_password: ${{ secrets.SF_PASS }}
          dry_run: ''
          env: "prd" # Pass env variable
        if: steps.manual_validation_prd.outputs.approved == 'true'